{% set name = "trustpy-tools" %}
{% set version = "2.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TrustPy/TrustPy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0adafd8b371309b65c97f3a81d334f6e4f1337fb6e892fcb662ca18da3754fea
  
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.20
    - scikit-learn >=1.0
    - matplotlib-base >=3.0

test:
  imports:
    - trustpy
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
    
about:
  home: https://github.com/TrustPy/TrustPy
  license: MIT
  license_file: LICENSE
  summary: 'Provides pre-deployment trustworthiness analysis and reliability metrics for AI/ML models.'
  description: |
    TrustPy is a production-ready Python package purpose-built for MLOps pipelines—enabling automated,
    interpretable analysis of model trustworthiness and predictive reliability before deployment.
    
    To contribute or collaborate, please contact Erim Yanik (erimyanik@gmail.com).
    
extra:
  recipe-maintainers:
    - yaniker
