{% set name = "trustpy-tools" %}
{% set version = "2.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TrustPy/TrustPy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 29475e9ef59dabfede4cbc8a65fd8118c14c36d68a92a1f6d80efb0baffa10db
  
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.20
    - scikit-learn >=1.0
    - matplotlib-base >=3.0

test:
  imports:
    - trustpy
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
    
about:
  home: https://github.com/TrustPy/TrustPy
  license: MIT
  license_file: LICENSE
  summary: 'Trustworthiness analysis and reliability metrics for predictive models.'
  description: |
    TrustPy is a Python library that provides a set of tools for analyzing and quantifying 
    trustworthiness in predictive models. It works out-the-box with the AI/ML packages and is
    actively growing with the addition of new metrics and techniques.
    
    To contribute or collaborate, please contact Erim Yanik (erimyanik@gmail.com).
    
extra:
  recipe-maintainers:
    - yaniker
